name: Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    prettier:
      name: 'Prettier'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Setup pnpm
          uses: pnpm/action-setup@v4.0.0
  
        - name: Use Node.js 22
          uses: actions/setup-node@v4
          with:
            node-version: '22'
            cache: 'pnpm'
  
        - name: Install dependencies
          run: pnpm install --frozen-lockfile --prefer-offline
  
        - name: Run Prettier check
          run: pnpm run prettier-check
  
    eslint:
      name: 'ESLint'
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run ESLint check
        run: pnpm run lint

    types:
      name: 'TypeScript'
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run TypeScript type check
        run: pnpm run type-check

    test:
      name: 'Test'
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [18, 20, 21, 22]
      steps:
      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          pnpm-version: 10.2.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Run tests
        run: pnpm test --if-present